CREATE TABLE DISCO(
   NroSerie INTEGER PRIMARY KEY,
    TitoloAlbum TEXT (20) NOT NULL,
    Anno VARCHAR(255)  NULL,
    Prezzo VARCHAR(255) NOT NULL
    );


CREATE TABLE CONTIENE(
    NroSerieDisco INTEGER PRIMARY KEY,
    CodiceReg VARCHAR(255) NOT NULL,
    NroProg INTEGER NOT NULL
    );


CREATE TABLE ESECUZIONE(
    CodiceReg VARCHAR(255) NOT NULL PRIMARY KEY,
    TitoloCanz TEXT (20) NOT NULL,
    Anno  VARCHAR(255) DEFAULT NULL
    );


CREATE TABLE  AUTORE(
    Nome TEXT (30) NOT NULL,
    TitoloCanz TEXT (20) NOT NULL
    );


CREATE TABLE   CANTANTE(
    NomeCantante TEXT (30) NOT NULL,
    CodiceReg VARCHAR(255) NOT NULL
    );


INSERT INTO DISCO(NroSerie,TitoloAlbum,Anno,Prezzo) VALUE
('1','RANDOM','2000','19.99'),
('2','BABYBOY','2001','9.99');
INSERT INTO CONTIENE(NroSerieDisco,CodiceReg, NroProg) VALUE
('1','A10','76'),
('2','B24','08');
INSERT INTO ESECUZIONE( CodiceReg ,TitoloCanz,Anno) VALUE
('A10','BARABI','2000'),
('B24','MARS','');
INSERT INTO AUTORE( Nome,TitoloCanz) VALUE
('DARIO.G','BARABI'),
('MULLER','MARS');
INSERT INTO CANTANTE( NomeCantante,CodiceReg) VALUE
('DARIO.G','A10'),
('SARAH','B24');

SELECT *
FROM DISCO
INNER JOIN CONTIENE
ON DISCO.NroSerie = CONTIENE.NroSerieDisco;

SELECT DISTINCT AUTORE.Nome
FROM AUTORE
INNER JOIN ESECUZIONE ON AUTORE.TitoloCanz = ESECUZIONE.TitoloCanz
INNER JOIN CANTANTE ON ESECUZIONE.CodiceReg = CANTANTE.CodiceReg
WHERE AUTORE.Nome LIKE 'D%';

SELECT DISTINCT TitoloAlbum
FROM DISCO
INNER JOIN CONTIENE
ON DISCO.NroSerie = CONTIENE.NroSerieDisco
INNER JOIN ESECUZIONE
ON CONTIENE.CodiceReg = ESECUZIONE.CodiceReg
WHERE ESECUZIONE.Anno ='';
